[package]
name = "testing_interface_0"
version = "0.1.0"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition = "2021"

[dependencies]
abi_stable = { version = "*", path = "../../../abi_stable" }
